name: mg

channels:
- metagraph/label/dev
- conda-forge

dependencies:
# dev environment
  - python=3.8
  - metagraph-dev
  - black

# dependencies (so setup.py develop doesn't pip install them)
  - metagraph>=0.2.6
  - metagraph-numba
  - mlir-graphblas
  
